import Footer from "./components/footer";
import Navbar from "./components/navbar";
import styles from './page.module.css'
import Introduction from "./components/introduction";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body className={styles.body}>
        <header><Navbar/></header>
          <Introduction />
          {children}
        <footer><Footer/></footer>
      </body>
    </html>
  )
}
